# azure-pipelines.yml
trigger:
  branches:
    include:
      - main

pool:
  name: 'selfpool'

steps:

  - script: pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: pytest
    displayName: 'Run tests'
