name: Run Pytest Automation on Multiple OS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests and Generate HTML Report
        run: |
          pytest --html=reports/pytest-html-report.html
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Upload Pytest HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report-${{ runner.os }}
          path: reports/pytest-html-report.html
      - name: Email HTML Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: Pytest Report
          to: vbhadra06@gmail.com
          from: GitHub Action
          body: |
            Hi,
            
            The latest pytest report is attached.
            
            Regards,
            CI Bot
          attachments: reports/pytest-html-report.html
