name: Run Pytest Automation on Multiple OS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Add PYTHONPATH to support relative imports
      - name: Set PYTHONPATH
        if: runner.os != 'Windows'
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Set PYTHONPATH (Windows)
        if: runner.os == 'Windows'
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $env:GITHUB_ENV

      - name: Run Tests and Generate HTML Report
        run: |
          pytest --html=reports/pytest-html-report.html

      - name: Upload Pytest HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report-${{ runner.os }}
          path: reports/pytest-html-report.html
